swagger: '2.0'
info:
  title: Hawk-Eyes
  description: |
    Hawk-Eyes admin services
  version: 0.0.1
basePath: /hawkeyes/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /administrative:
    get:
      operationId: admin-service_sampleGetUsersService
      summary: fetches users
      description: fetches users
      tags:
      - account
      parameters:
        # - $ref: '#/parameters/authorization'
        - $ref: '#/parameters/someSampleParam'
      responses:
        '200':
          $ref: '#/responses/AdminResponse'
        '400':
          $ref: '#/responses/BadRequest'
        '404':
          $ref: '#/responses/NoResult'
parameters:
  authorization:
    name: authorization
    in: header
    type: string
    description: The authorization bearer token
    required: true
  someSampleParam:
    name: someSampleParam
    in: query
    type: string
    description: someSampleParam 
    required: true
responses:
  AdminResponse:
    description: response to valid admin call
    schema: 
      $ref: "#/definitions/AnyModel"
  BadRequest:
    description: bad request
    schema:
      $ref: '#/definitions/Error'
  NoResult:
    description: result not found
    schema:
      $ref: '#/definitions/Error'
  UnauthorizedError:
    description: user is not an authorized to access service
    schema:
      $ref: '#/definitions/Error'        
definitions:
  AnyModel:
    type: object
  AnyArrayModel:
    type: array
    items:
      $ref: "#/definitions/AnyModel"         
  AdminModelParam:
    type: object
    required: 
      - verb
      - path
    properties:
      verb:
        type: string
        enum: ['GET', 'POST', 'PUT' , 'DELETE', 'PATCH', 'HEAD']
        description: HTTP Verb ('GET', 'POST', 'PUT' , 'DELETE', 'PATCH', 'HEAD')
      path:
        type: string
        description: Path part of URL (e.g. /my_path in URL https://myserver.com/my_path)
      payload:
        $ref: '#/definitions/AnyModel'
      payloads:
        $ref: '#/definitions/AnyArrayModel'
  Error:
    type: object
    additionalProperties: false
    properties:
      message:
        type: string
      details:
        type: object
